#!/bin/bash
read -p "x = " x
read -p "y = " y
read -p "operator: " opr

# t4
if [ "$1" = "-s" ]
then
    outfile=$2
fi

case $opr in
    +) result=$((x + y)) ;;
    -) result=$((x - y)) ;;
    \*) result=$((x * y)) ;;
    /) result=$((x / y)) ;;
    %) result=$((x % y)) ;;
    *) echo "Invalid operation"; exit 1 ;;
esac

if [ -n "$outfile" ]
then
    echo "$x $opr $y = $result" >> "$outfile"
fi

echo "$x $opr $y = $result"